
- name: name of playbook
  hosts: all
  tasks:
  - name: Copy WAR-file from Jenkins to tomcat
    copy:
      src: /var/jenkins_home/workspace/miniprojekt@2/target/webblog.war
      dest: /usr/local/tomcat/webapps
      mode: '0644'
