- name: name of playbook
  hosts: all
  connection: docker
  tasks:
  - name: Copy WAR-file from Nexus to tomcat
    copy:
      src: spring-boot-webblog-0.0.1-SNAPSHOT.war
      dest: /usr/local/tomcat/webapps
      mode: '0644'
