- name: name of playbook
  hosts: all
  connection: docker
  tasks:
  - name: Copy WAR-file from Jenkins to tomcat
    copy:
      src: /var/jenkins_home/workspace/miniprojekt/target/spring-boot-webblog-0.0.1-SNAPSHOT.war
      dest: /usr/local/tomcat/webapps
      mode: '0777'
